site_name: West Ada School District Board of Trustees Section 400 Rework
theme:
  name: material
  custom_dir: overrides
  logo: img/logo.png
markdown_extensions:
  - footnotes
  - meta
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - search
  - autolinks
extra:
  generator: false