site_name: West Ada School District Policies
exclude_docs: |
  meetings/
theme:
  name: material
  custom_dir: overrides
  logo: img/logo.png
markdown_extensions:
  - footnotes
  - meta
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - search
  - autolinks
  - exporter:
      buttons:
        - title: Download as PDF
          icon: material-file-download-outline
          enabled: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.enabled
          attributes: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.attributes
      formats:
        pdf:
          enabled: !ENV [MKDOCS_EXPORTER_PDF_ENABLED, true]
          concurrency: 16
extra:
  generator: false