site_name: West Ada School District Policies
exclude_docs: |
  meetings/
theme:
  name: material
  custom_dir: overrides
  logo: img/logo.png
markdown_extensions:
  - footnotes
  - meta
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - search
  - autolinks
  - to-pdf:
      author: West Ada School District Board of Trustees
      copyright: © 2025 West Ada School District
      cover: true
      back_cover: false
      cover_title: West Ada School District
      cover_subtitle: Policy Manual
      cover_logo: docs/img/logo.png
      toc_title: Table of Contents
      heading_shift: true
      toc_level: 3
      ordered_chapter_level: 0
      exclude_pages:
         - 'meetings/'
      output_path: pdf/document.pdf
      debug_html: false
      show_anchors: false
      download_link: header
      verbose: false
      # enabled_if_env: '1'
extra:
  generator: false