site_name: West Ada School District Board of Trustees
theme:
  name: material
  custom_dir: overrides
  logo: img/logo.png
markdown_extensions:
  - footnotes
  - meta
  - tables
plugins:
  - search
  - autolinks
  - with-pdf
extra:
  generator: false